/**
 * @file src/routes/web/chat/message-routes.js
 * @description 聊天路由子分组。
 */

function registerChatMessageRoutes(app, ctx) {
  const {
    requireAuth,
    updateConversationTitle,
    getConversationById,
    addMessage,
    invalidateConversationCache,
    generateReplyViaGateway,
    logger,
    renderPage,
    buildChatRequestContext,
    parseIntegerField,
    parseIdParam,
    getClientIp,
    hitLimit,
    buildNextConversationTitle,
    renderChatPage,
    loadConversationForUserOrFail,
    buildConversationCharacterPayload,
    buildChatMessagePacket,
    createNdjsonResponder,
    streamChatReplyToNdjson
  } = ctx;

  app.post('/chat/:conversationId/message', requireAuth, async (req, res, next) => {
    let conversationId;
    try {
      conversationId = parseIdParam(req.params.conversationId, '会话 ID');
      const rawContent = String(req.body.content || '');
      const limited = await hitLimit(`rate:chat-message:${req.session.user.id}:${getClientIp(req)}`, 60, 30);
      if (limited) {
        return renderPage(res, 'message', { title: '提示', message: '发送太频繁，请稍后再试。' });
      }
      const parentMessageId = parseIntegerField(req.body.parentMessageId, { fieldLabel: '父消息 ID', min: 1, allowEmpty: true });

      const conversation = await loadConversationForUserOrFail(req, res, conversationId);
      if (!conversation) {
        return;
      }

      const chatRequest = await buildChatRequestContext(req, conversation, rawContent, parentMessageId);
      const { isFirstTurn, content, history, promptKind } = chatRequest;

      if (!content) {
        return renderPage(res, 'message', { title: '提示', message: '消息不能为空。' });
      }

      const userMessageId = await addMessage({
        conversationId,
        senderType: 'user',
        content,
        parentMessageId,
        branchFromMessageId: parentMessageId,
        promptKind: isFirstTurn ? 'conversation-start' : 'normal',
        metadataJson: JSON.stringify({
          requestId: req.requestId,
          operation: 'user-message',
          autoGenerated: isFirstTurn && !rawContent.trim(),
        }),
      });

      const reply = await generateReplyViaGateway({
        requestId: req.requestId,
        userId: req.session.user.id,
        conversationId,
        character: {
          name: conversation.character_name,
          summary: conversation.character_summary,
          personality: conversation.personality,
          prompt_profile_json: conversation.prompt_profile_json,
        },
        messages: history,
        userMessage: content,
        promptKind,
        modelMode: conversation.selected_model_mode || 'standard',
        user: req.session.user,
      });

      const replyMessageId = await addMessage({
        conversationId,
        senderType: 'character',
        content: reply,
        parentMessageId: userMessageId,
        branchFromMessageId: userMessageId,
        promptKind: isFirstTurn ? 'conversation-start' : 'normal',
        metadataJson: JSON.stringify({
          requestId: req.requestId,
          operation: 'assistant-reply',
        }),
      });

      await updateConversationTitle(conversationId, buildNextConversationTitle(conversation, content));
      return res.redirect(`/chat/${conversationId}?leaf=${replyMessageId}`);
    } catch (error) {
      const isQuotaError = error.message === 'REQUEST_QUOTA_EXCEEDED' || error.message === 'TOKEN_QUOTA_EXCEEDED';
      if (!isQuotaError && conversationId) {
        try {
          const conv = await getConversationById(conversationId, req.session.user.id);
          if (conv) {
            return await renderChatPage(req, res, conv, {
              errorMessage: 'AI 回复失败，请稍后重试。如持续出现，请联系管理员。',
            });
          }
        } catch (_) { /* 渲染失败时降级到全局错误处理 */ }
      }
      return next(error);
    }
  });

  app.post('/chat/:conversationId/message/stream', requireAuth, async (req, res, next) => {
    let conversationId;
    const ndjson = createNdjsonResponder(req, res);
    try {
      conversationId = parseIdParam(req.params.conversationId, '会话 ID');
      const rawContent = String(req.body.content || '');
      const limited = await hitLimit(`rate:chat-stream:${req.session.user.id}:${getClientIp(req)}`, 60, 30);
      if (limited) {
        ndjson.safeWrite({ type: 'error', message: '发送太频繁，请稍后再试。' });
        ndjson.end();
        return;
      }
      const parentMessageId = parseIntegerField(req.body.parentMessageId, { fieldLabel: '父消息 ID', min: 1, allowEmpty: true });

      const conversation = await loadConversationForUserOrFail(req, res, conversationId);
      if (!conversation) {
        ndjson.end();
        return;
      }

      const chatRequest = await buildChatRequestContext(req, conversation, rawContent, parentMessageId);
      const { isFirstTurn, content, history, promptKind } = chatRequest;

      if (!content) {
        ndjson.safeWrite({ type: 'error', message: '消息不能为空。' });
        ndjson.end();
        return;
      }

      const userMessageId = await addMessage({
        conversationId,
        senderType: 'user',
        content,
        parentMessageId,
        branchFromMessageId: parentMessageId,
        promptKind: isFirstTurn ? 'conversation-start' : 'normal',
        metadataJson: JSON.stringify({
          requestId: req.requestId,
          operation: 'user-message',
          autoGenerated: isFirstTurn && !rawContent.trim(),
          delivery: 'stream',
        }),
      });

      const userPacket = await buildChatMessagePacket(req, conversation, userMessageId, userMessageId);
      ndjson.safeWrite({
        type: 'user-message',
        conversationId,
        userMessageId,
        content,
        messageId: userMessageId,
        leafId: userMessageId,
        html: userPacket ? userPacket.html : '',
      });
      ndjson.safeWrite({ type: 'assistant-start', conversationId, parentMessageId: userMessageId, mode: 'message' });

      const replyContent = await streamChatReplyToNdjson({
        requestId: req.requestId,
        userId: req.session.user.id,
        conversationId,
        character: buildConversationCharacterPayload(conversation),
        messages: history,
        userMessage: content,
        promptKind,
        modelMode: conversation.selected_model_mode || 'standard',
        signal: ndjson.abortController.signal,
        safeWrite: ndjson.safeWrite,
        user: req.session.user,
      });

      if (ndjson.isClosed() || ndjson.abortController.signal.aborted) {
        const partialReply = String(replyContent || '').trim();
        if (partialReply) {
          const partialReplyMessageId = await addMessage({
            conversationId,
            senderType: 'character',
            content: partialReply,
            parentMessageId: userMessageId,
            branchFromMessageId: userMessageId,
            promptKind: isFirstTurn ? 'conversation-start' : 'normal',
            status: 'streaming',
            metadataJson: JSON.stringify({
              requestId: req.requestId,
              operation: 'assistant-reply-stream-interrupted',
              interrupted: true,
            }),
          });
          await updateConversationTitle(conversationId, buildNextConversationTitle(conversation, content));
          logger.warn('Persisted interrupted assistant stream as partial message', {
            requestId: req.requestId,
            conversationId,
            userMessageId,
            partialReplyMessageId,
          });
        } else {
          logger.warn('Assistant stream interrupted before any reply content', {
            requestId: req.requestId,
            conversationId,
            userMessageId,
          });
        }
        return;
      }

      const replyMessageId = await addMessage({
        conversationId,
        senderType: 'character',
        content: replyContent,
        parentMessageId: userMessageId,
        branchFromMessageId: userMessageId,
        promptKind: isFirstTurn ? 'conversation-start' : 'normal',
        metadataJson: JSON.stringify({
          requestId: req.requestId,
          operation: 'assistant-reply-stream',
        }),
      });

      await updateConversationTitle(conversationId, buildNextConversationTitle(conversation, content));
      await invalidateConversationCache(conversationId);
      const replyPacket = await buildChatMessagePacket(req, conversation, replyMessageId, replyMessageId);
      const parentPacket = await buildChatMessagePacket(req, conversation, replyMessageId, userMessageId);
      ndjson.safeWrite({
        type: 'done',
        conversationId,
        replyMessageId,
        messageId: replyMessageId,
        leafId: replyMessageId,
        full: replyContent,
        mode: 'message',
        html: replyPacket ? replyPacket.html : '',
        parentMessageId: userMessageId,
        parentHtml: parentPacket ? parentPacket.html : '',
      });
      ndjson.end();
      return;
    } catch (error) {
      if (!res.headersSent) {
        return next(error);
      }
      ndjson.fail(error);
    }
  });
}

module.exports = { registerChatMessageRoutes };
