/**
 * @file scripts/build-css.js
 * @description 将 public/styles/site-pages.src.css 中的本地 @import 递归内联到 site-pages.css，减少首屏 CSS 串行请求。
 */

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.join(__dirname, '..');
const sourceEntry = path.join(projectRoot, 'public/styles/site-pages.src.css');
const outputEntry = path.join(projectRoot, 'public/styles/site-pages.css');

function expandCss(filePath, seen = new Set()) {
  const absolutePath = path.resolve(filePath);
  if (seen.has(absolutePath)) return '';
  seen.add(absolutePath);

  const baseDir = path.dirname(absolutePath);
  return fs.readFileSync(absolutePath, 'utf8')
    .split(/\r?\n/)
    .map((line) => {
      const match = line.trim().match(/^@import\s+url\(["'](.+?)["']\);?$/);
      if (!match) return line;
      const importPath = path.resolve(baseDir, match[1]);
      const relativePath = path.relative(path.dirname(outputEntry), importPath).replace(/\\/g, '/');
      return [
        `/* --- begin ${relativePath} --- */`,
        expandCss(importPath, seen),
        `/* --- end ${relativePath} --- */`,
      ].join('\n');
    })
    .join('\n');
}

const output = [
  '/*',
  ' * Aggregated site page stylesheet.',
  ' *',
  ' * Generated by scripts/build-css.js from public/styles/site-pages.src.css.',
  ' * Keep this file as the only template-level entrypoint:',
  ' *   <link rel="stylesheet" href="/public/styles/site-pages.css" />',
  ' */',
  '',
  expandCss(sourceEntry),
].join('\n').split('\n').map((line) => line.replace(/[ \t]+$/g, '')).join('\n');

fs.writeFileSync(outputEntry, output);
console.log(`[build-css] wrote ${path.relative(projectRoot, outputEntry)} (${output.length} bytes)`);
